### ISSUE TITLE
Closing like a tab

### ISSUE THREAD

**Issue by davetoxa** [atom/markdown-preview#101]
I've got a bad experience with closing this panel
Could you give opportunity toogle `ctrl-shift-m` open->close or something link cmd+w

**Comment by dorkrawk** [comment]
So I'm seeing this issue again.

I can open a Markdown preview with `ctrl-shift-m`, but when I close it (with the same keystroke) the preview goes away but the pane stays.

Atom 1.1.0
OSX 10.11.1
