### ISSUE TITLE
Scroll to the edit location in the preview window

### ISSUE THREAD

**Issue by joshuawarner32** [atom/markdown-preview#139]
Mac OS 10.9, Atom 0.120.0, markdown-preview 0.93.0
### Scenario
- I create / edit a markdown document using markdown-preview
- I have enough content to run off the screen in the preview window (i.e. I can scroll)
- I scroll to the bottom of both the editor and the preview
- I add new lines / paragraphs at the end of the document
### Expectation

The preview window should scroll so that the content I'm adding is in view
### Actual result

The preview window maintains it's scroll state where it was before, which means every time I add new lines, I have to manually scroll the preview down to see it.
### Discussion

The ideal solution (in my mind) consists of tracking the cursor across the markdown rendering transform.  Then, whenever the markdown preview is redrawn because of changes in the document, always make sure that the part of the document that I'm editing in the editor is visible in the preview window.

Barring that, it shouldn't be hard to special-case editing the end of a document, since that's by far the most annoying case.  It's also trivial to match the end of the document with the end of the generated markdown.

Another solution would be to allow scrolling the preview window down past the end of the document.  This would be a-typical, at least on mac - but many windows and linux editors let you scroll down until the last line of your document is actually at the top of the view.

**Comment by mark-hahn** [comment]
This should give you what you want.. https://atom.io/packages/markdown-scroll-sync.
