### ISSUE TITLE
Ctrl-shift-m not working for files outside of Markdown Preview directory

### ISSUE THREAD

**Issue by andrekibbe** [atom/markdown-preview#156]
When I try to preview a .md file with `ctrl-shift-m` on most files, nothing happens, but when I select _Open in Atom_ from the package options in Settings, the .md docs that are in the sidebar under the markdown-preview folder do actually preview.

Is this by design? Is it not possible to access the preview globally, for any Markdown file in any directory?

**Comment by Sogl** [comment]
Same here. 
`Ctrl + Shift + M` not working at all, I can enable preview mode only with `Ctrl + Shift + P` -> `Markdown Toggle: Preview`.

Env:
* Windows 7 x64
* Atom 1.7.1
* Markdown preview 0.158.0

**Comment by RafaelKr** [comment]
For me it's working, if I select the file from Tree View, but if I open it from Filemanager or with "File Open (Ctrl+O)", nothing happens.
