### ISSUE TITLE
markdown preview cover up some characters

### ISSUE THREAD

**Issue by redhatlinux10** [atom/markdown-preview#169]
i am writing a blog which contains both Chinese characters and English characters.  nothing i can tell more than pictures.

before covered up, i have already made anotations on these covered up characters :
![](http://i1317.photobucket.com/albums/t638/redhatlinux10/misc/markdown-preview-cover-up-1_zps1a43933d.png)
after covered up:
![](http://i1317.photobucket.com/albums/t638/redhatlinux10/misc/markdown-preview-cover-up-2_zps0e5d1d9c.png)

**Comment by kevinsawicki** [comment]
@lee-dohm I believe you are right, closing it out.
