### ISSUE TITLE
`Enter` key cannot use after markdown doc previewed

### ISSUE THREAD

**Issue by 1ternal** [atom/markdown-preview#172]
When I previewed my doc then close preview pane, I cannot use `Enter` key in the .md file.
I'v to reopen atom editor to use `enter` key with this md file.

There was no problem before upgrade to atom version 0.169

I'm using aluratek brand kvm switch, Mac Yosemite. I' not sure is this related.

**Comment by benogle** [comment]
Do you have the emmet package installed?

**Comment by 1ternal** [comment]
yes, I've install Emmet version 2.3.0;
and after disable emmet, everything works fine! :smile:

**Comment by lee-dohm** [comment]
Closing as duplicate of emmetio/emmet-atom#186.
