### ISSUE TITLE
Live Update does not save position

### ISSUE THREAD

**Issue by karai17** [atom/markdown-preview#178]
So I am writing a Markdown file and I have live update on because live update is great. The problem is, The preview is now longer than my screen and the live update force scrolls to the top of the page instead of either staying where I scroll it to, or scrolling with the text as it grows off screen.

It gets a bit annoying to have to continuously select the preview panel and scroll down.

**Comment by Code-Vortex** [comment]
:+1: , I thought I am the only one who have this issue !

**Comment by itamayo** [comment]
Here a personal implementation : https://github.com/atom/markdown-preview/pull/193

**Comment by SashaOv** [comment]
+1

**Comment by Code-Vortex** [comment]
In my case i have *.js not *.coffee, however the repo for markdown-preview
has *.coffee
Note: the editor and plugin is up-to-date

**Comment by itamayo** [comment]
On apm installation I think is compiled to *.js, any case the change is moreless the same:
line:153 add:  
editor.onDidChangeScrollTop(function(e) {
            markdownPreviewView.scrollTop(e);
        });

**Comment by stevenroose** [comment]
This is a major issue when working with larger Markdown documents. Please make this work!

**Comment by kdelmonte** [comment]
Having the same issue.

**Comment by Fania** [comment]
Synced scrolling would be great!

**Comment by LouisTakePILLz** [comment]
:+1: I'd really like to see this happen.

**Comment by prashantv** [comment]
I'm still seeing this issue. I'm on OSX (10.10.3) and using 0.194.0

I tried safe mode (`atom --safe`) and still reproduced the issue, uploaded a video here:
https://drive.google.com/file/d/0B1l0iMj29vl7VmNrajBWdThwR0U/view

**Comment by pcarolan** [comment]
I'm also having this issue.

**Comment by ryl** [comment]
+1 I'm also having this problem on 0.204.0

**Comment by jarruda** [comment]
Issue present in version 0.209, OSX 10.10.3

**Comment by danielvy** [comment]
This issue is still present.

Atom 1.0.7
markdown-preview 0.150
Mac OSX 10.10.5

**Comment by cedricvanrompay** [comment]
Still present.

OS: Gnome-Ubuntu 14.04 LTS
Atom: 1.8.0
Mardown-Preview: 0.158.0

**Comment by JAAdrian** [comment]
This issue is still not fixed and very present!

Atom 1.12.4 on
Xubuntu 16.04.1
Linux Mint 18
Windows 10

**Comment by SreehariRamMohan** [comment]
Still Present +1 let's get this fixed!
