### ISSUE TITLE
preview not working with atom version 0.175.0

### ISSUE THREAD

**Issue by opennomad** [atom/markdown-preview#180]
I found that in 0.175.0 the preview pane shows up, but no rendered content is visible. Downgrading to 0.174.0 corrects this. This is on Ubuntu 14.10, running the .dpkg from the atom releases page.

**Comment by simurai** [comment]
@opennomad Not sure if it's the same, but there was a recent discussion on https://discuss.atom.io/t/markdown-previewer-is-blank/14438

**Comment by opennomad** [comment]
@simurai thanks for the pointer. To test I tried the newest release of atom (0.176.0) and there the preview appears to be working as expected again.
