### ISSUE TITLE
can't review table

### ISSUE THREAD

**Issue by windgo** [atom/markdown-preview#186]
it's show correct in the editor Mou.	
| 状态标识 |状态消息 | 状态说明 |
	|:-------|:----|:-----|
	|0|成功|发布成功|
	|1|失败|发布失败|

**Comment by kevinsawicki** [comment]
What issue are you seeing in Atom with the way it is rendered? Could you include a screenshot?

This is how it looks for me which appears to be rendering correctly.

![screen shot 2015-02-02 at 6 03 36 pm](https://cloud.githubusercontent.com/assets/671378/6013173/d5d23c66-ab05-11e4-8772-be4885b748ff.png)

**Comment by izuzak** [comment]
@windgo can you share the exact steps which reproduce the problem for you and the version of Atom you are using?

**Comment by izuzak** [comment]
Closing this as we can't reproduce and the given example renders correctly for at least two users. Happy to reopen if you can share steps to reproduce, @windgo.
