### ISSUE TITLE
Code blocks are impossible to read

### ISSUE THREAD

**Issue by lexicalunit** [atom/markdown-preview#194]
Probably need to tweak the background color of code blocks. As it is now pretty much all code blocks, no matter the language, are impossible to read.

```
$ apm list | grep markdown
├── markdown-preview@0.132.0
$ atom --version
0.177.0
```

![screen shot 2015-02-11 at 10 29 00 am](https://cloud.githubusercontent.com/assets/1903876/6151082/2632ab1c-b1d9-11e4-9239-5b1203214251.png)

**Comment by lee-dohm** [comment]
Looks like it is an issue with your theme?

![screen shot 2015-02-11 at 9 07 46 am](https://cloud.githubusercontent.com/assets/1038121/6151857/87f56d32-b1cd-11e4-8620-dfeed43f9d23.png)

**Comment by lexicalunit** [comment]
Confirmed, it's a theme issue. My bad. Fixed it by modifying my Atom's `style.less` file:

```less
.markdown-preview {
  atom-text-editor {
    background: #222;
  }
}
```

**Comment by lee-dohm** [comment]
No problem. I'm glad I could help!
