### ISSUE TITLE
Conversion to HTML loses code blocks

### ISSUE THREAD

**Issue by jlwollam** [atom/markdown-preview#195]
My markdown looks great in the preview, but when I save to html all my code blocks are gone. It appears to make a code block, but none of my code is in the HTML anywhere. It used to create "pre" blocks to format, but now it places in "atom-text-editor" tags that are empty where the code should be. I know atom had some breaking changes recently and have to assume this is related. Is this in the scope of markdown-preview and has it been addressed? Is there anything I can do to help? Thank you.

**Comment by izuzak** [comment]
Thanks for the report, I can reproduce this.

What Atom shows:

![screen shot 2015-02-12 at 14 07 22](https://cloud.githubusercontent.com/assets/38924/6167942/af0516cc-b2c0-11e4-89df-089725700d76.png)

What I get after I use "Copy as HTML" (notice the content-less `<atom-text-editor> element`):

```
<p>foo</p>
<atom-text-editor class="editor" callattachhooks="true" gutter-hidden="" data-grammar="source ruby" data-encoding="utf8"><div class="underlayer"></div><div class="overlayer"></div></atom-text-editor>
<p>baz</p>
```

cc @nathansobo @kevinsawicki for :eyes:

**Comment by nathansobo** [comment]
As a workaround, running the `markdown-preview:copy-html` command in the source editor should still work. Didn't realize there was another code path.

**Comment by nathansobo** [comment]
The fix will be released in `v0.180.0`. For the time being, use the workaround mentioned above.

**Comment by izuzak** [comment]
:sparkle: @nathansobo

**Comment by nathansobo** [comment]
Looks like CI doesn't like my fix. Working on this now.

**Comment by jlwollam** [comment]
Thanks guys! That was fast :)
