### ISSUE TITLE
"Scroll Past End" affects code fences

### ISSUE THREAD

**Issue by LouisTakePILLz** [atom/markdown-preview#209]
The `scrollPastEnd` option seems to interfere with the generated code fences (`atom-text-editor` elements); I highly doubt this is intended behavior for code fences.

Here's a nice GIF showing the issue at hand:

![atom markdown-preview scrollpastend bug](https://cloud.githubusercontent.com/assets/920910/6498843/0a6c2010-c2bf-11e4-9f8b-43b6526cce87.gif)

**Atom version**: 0.186.0
**Package version**: 0.137.0
**Operating system**: Windows 7 64-bit

**Comment by envygeeks** [comment]
Any update on this because this is pretty old and it constantly gets in the way of touchpad scroll.

**Comment by Annonomus-Penguin** [comment]
+1

**Comment by abdonrd** [comment]
+1

**Comment by envygeeks** [comment]
Please lock this issue to stop endless spams.

**Comment by 50Wliu** [comment]
Closing in favor of #245 because that issue has some more debate.
