### ISSUE TITLE
Save 'as' fails to include editor style

### ISSUE THREAD

**Issue by ArnaudRinquin** [atom/markdown-preview#212]
Hey guys,

Although the `Save as HTML` was my PR, I failed to properly implement it. For some reason, the tests work but not the actual feature: the `atom-text-editor` styles are not integrated.

From what I understand, it's because the `atom-text-editor` element shadow DOM processing is asynchronous and my code retrieve the styles synchronously.

I successfully fix the problem by adding a one second timeout but this is obviously not the right way to fix it. I was not successful on finding what event is triggered when shadow DOM processed.

Sorry about delivering a broken feature, working on a fix right now.

**Comment by abe33** [comment]
Have you tried @kevinsawicki suggestion of using an `atom-style` node instead of an `atom-text-editor`?

**Comment by ArnaudRinquin** [comment]
That's what's done at the moment:

```coffee
textEditorStyles = document.createElement("atom-styles")
textEditorStyles.setAttribute "context", "atom-text-editor"
document.body.appendChild textEditorStyles
```

The problem is that the `<style>` children elements I am expecting aren't added synchronously. I don't know what event is triggered when they are.

**Comment by abe33** [comment]
Oh I see, sorry. 

Looks like there's some events available on the `atom-styles` element: https://github.com/atom/atom/blob/master/src/styles-element.coffee#L7-L14

Not sure if it'll help as you won't know when all styles have been added (which suppose knowing how many styles have to be added).

**Comment by ArnaudRinquin** [comment]
Thanks for pointing to `style` element events but yeah, has you said, no way to know when all the styles are added. This probably requires a new event to be added to `style` element.

**Comment by ArnaudRinquin** [comment]
#213 should fix it.

**Comment by nathansobo** [comment]
Closes #213.

**Comment by 50Wliu** [comment]
@nathansobo I assume you wanted to close this?

**Comment by nathansobo** [comment]
Thanks a ton for helping track everything @50Wliu.
