### ISSUE TITLE
Table dose not working

### ISSUE THREAD

**Issue by professormahi** [atom/markdown-preview#219]
Hi,  
Why `Tables` dose not working in your previews ?
| Header One     | Header Two     |  
 | :------------- | :------------- |  
  | Item One       | Item Two       |  

this is what I'm using to have table,   
Thanks

**Comment by izuzak** [comment]
Can you try removing the empty lines?

This works for me:

![screen shot 2015-03-20 at 15 15 44](https://cloud.githubusercontent.com/assets/38924/6753106/0269375c-cf14-11e4-9cd9-a0caba591dd3.png)

The syntax you are using with empty lines doesn't even work in GitHub comments. Can you clarify why you expected that to work?

**Comment by professormahi** [comment]
Thaanks, It have been solved
