### ISSUE TITLE
Hope to have more styles to choose

### ISSUE THREAD

**Issue by chaosink** [atom/markdown-preview#224]

**Comment by lee-dohm** [comment]
As can be seen in #135, there is already a method of customizing your Markdown Preview stylesheet. Is that what you're looking for?

**Comment by izuzak** [comment]
Closing this since no other information was provided and there's a linked issue with examples of customizing the styles. @chaosink let us know if you have any questions or want to clarify your request.

**Comment by chaosink** [comment]
I'm sorry for not leaving more information. Thanks for the answer so much!
