### ISSUE TITLE
utf markdown html mangled

### ISSUE THREAD

**Issue by 50Wliu** [atom/markdown-preview#226]
_From @m4b on March 27, 2015 22:28_

It seems like utf-8 symbols are mangled when saving a markdown file as html (on OSX Yosemite).

For example:

>#Example
>
>The More You Know™
>
>ಠ_ಠ

is rendered as the following html:

>Example
>
>The More You Knowâ„¢
>
>à² _à² 

It shows up fine using the built-in Markdown Preview.

_Copied from original issue: atom/atom#6136_

**Comment by juaron** [comment]
Looks like this issue https://github.com/chjj/marked/issues/561.

**Comment by m4b** [comment]
I've verified this issue exists for linux as well.

Here's my `uname -a`

> Linux derp 3.18.6-1-ARCH #1 SMP PREEMPT Sat Feb 7 08:44:05 CET 2015 x86_64 GNU/Linux

**Comment by kevinsawicki** [comment]
Fixed by #227
