### ISSUE TITLE
fixed scroll postion

### ISSUE THREAD

**Issue by gimm** [atom/markdown-preview#228]
while eidting md file with the preview panel open aside, the preview panel will jump to the very top each time the md file changed.
Is there a way to make the preview stay where it is(keep the scroll position)? So that I can preview while editing.

**Comment by 50Wliu** [comment]
Please update to the latest Atom version (currently 0.188.0).  This has been fixed.

**Comment by prashantv** [comment]
I'm using version 0.194 and seeing the same issue.

**Comment by lee-dohm** [comment]
The original issue was reported as #178, I believe. You should probably comment there instead. Also, when you do reply there, could you give the following information?

* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?
