### ISSUE TITLE
Table background colour is overridden but no text colour is specified

### ISSUE THREAD

**Issue by alexrussell** [atom/markdown-preview#237]
Not a problem before, but one-dark-ui changes our background and text colours from underneath us.

![markdown bads](https://cloud.githubusercontent.com/assets/412784/7043698/8d193bf8-dde3-11e4-997e-139566c4dc4d.png)

Cross ref: atom/one-dark-ui#43

**Comment by simurai** [comment]
This will be fixed for the one-dark-ui theme in the next release.

There is another issue open about adapting the markdown-preview to themes: #6
