### ISSUE TITLE
I'm curious Why it can't show Chinese correctly?

### ISSUE THREAD

**Issue by yinwoods** [atom/markdown-preview#246]
I use markdown-preview in the atom editor, can you help me solve this problem?

**Comment by lee-dohm** [comment]
You probably need to style it to use a font that includes Chinese glyphs. There is a great post on [Discuss](https://discuss.atom.io), the official Atom message board, about how to fix this kind of thing for Hindi on the tree view:

https://discuss.atom.io/t/unicode-font-support-in-treeview/16310/4?u=leedohm

**Comment by lee-dohm** [comment]
Let us know if you need more help!

**Comment by 50Wliu** [comment]
Duplicate of #238, please subscribe there for updates.
