### ISSUE TITLE
Cmd+C on selected text in preview performs 'Copy As HTML'

### ISSUE THREAD

**Issue by hryamzik** [atom/markdown-preview#251]
That is a bit confusing. Selecting text and copying with a copy command works fine.

**Comment by izuzak** [comment]
@hryamzik I'm having trouble reproducing this. Which version of Atom are you using, which OS, and can you reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? Can you take a screenshot of the [keybinding resolver](https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings) when you press `cmd-c` in the preview with selected text?

**Comment by hryamzik** [comment]
@izuzak, sure! It's Atom Version 0.199.0 (0.199.0), Mac OS 10.10.3.

Looks like it's a bit more complicated then I expected: text should be copied from a code block. Key bindings resolver is empty.

![image](https://cloud.githubusercontent.com/assets/1643962/7724790/766b235e-fefd-11e4-8c1e-c10a08aa1b2e.png)

It reproduces in a safe mode as well.

**Comment by izuzak** [comment]
> Looks like it's a bit more complicated then I expected: text should be copied from a code block.

I'm not sure I understand what that means. Can you please clarify and provide the _exact_ steps which reproduce this problem for you, including a snippet of Markdown which you're previewing?

> Key bindings resolver is empty.

Interestingly, the keybinding resolver shows that you pressed `ctrl-shift-cmd`. I was assuming you were just pressing `cmd`. Can you confirm which keys you're pressing exactly and which keyboard layout you're using?

**Comment by hryamzik** [comment]
This comment contains a valid markdown to reproduce the eissue.

```
Here's a text we are going to copy
```

**Comment by hryamzik** [comment]
Key bindings resolver doesn't update on pressing the cmd+c or just shows cmd.
![image](https://cloud.githubusercontent.com/assets/1643962/7725004/565f7afe-feff-11e4-8c05-4fdd5bd23224.png)


Here're the steps:

1. Create a markdown file, add a code block to it. [This](251#issuecomment-103855408) comment contains a valid example.
2. Open markdown preview by pressing the ctrl+shift+m
3. Select some text in the code block in preview. In this example I'll select the ```text``` word.
4. Press cmd+c

Here's what I get in my clipboard:
```
<h1 id="issue-251">Issue #251</h1>
<pre class="editor-colors lang-text"><div class="line"><span class="text plain"><span class="meta paragraph text"><span>Here&#39;s&nbsp;a&nbsp;text&nbsp;we&nbsp;are&nbsp;going&nbsp;to&nbsp;copy</span></span></span></div></pre>
```

**Comment by izuzak** [comment]
Thanks for those steps, @hryamzik -- that's helpful, I can reproduce this now as well.

**Comment by hryamzik** [comment]
Great, sorry for not describing this properly in an initial comment.

**Comment by ricardofbarros** [comment]
+1

**Comment by xicombd** [comment]
+1

**Comment by garthk** [comment]
This is driving me nuts. The number of times I've pasted an entire window of HTML into my terminal instead of just the command text I have highlighted…

**Comment by ruffsl** [comment]
+1

**Comment by AaronV** [comment]
+1

**Comment by winterflags** [comment]
+1

**Comment by steveandroulakis** [comment]
No fix for this yet? I'm getting it in 1.8.0 Atom.

**Comment by jonfairman** [comment]
+1

**Comment by truebit** [comment]
+1 Really annoying.
Atom 1.8.0 
markdown-preivew 0.158

I cannot find `Copy` with right click when selected texts in preview pane. I used PopClip, I clicked `Copy` on PopClip popup. and it would give me the texts I needed.

**Comment by dreneral** [comment]
+1
