### ISSUE TITLE
Support copy with Keyboard shortcut when the Preview Window is focused

### ISSUE THREAD

**Issue by mnquintana** [atom/markdown-preview#259]
_From @rgl on May 31, 2015 18:6_

When we open the Preview Window, say when editing a `.md` file, let us press `Ctrl+C` to copy the selected text. Currently that only works from the context menu.

Please note that copying from a normal paragraph works, BUT if you select the text from a `Fenced code block` it wont work. I'm using Atom 0.204.0.

_Copied from original issue: atom/atom#7041_

**Comment by mnquintana** [comment]
_From @lee-dohm on May 31, 2015 18:24_

This belongs on the [markdown-preview package](https://github.com/atom/markdown-preview). Would you mind reopening the Issue there?

**Comment by garthk** [comment]
See also #251.

**Comment by ruffsl** [comment]
+1

**Comment by bagong** [comment]
Maybe related: if you copy text from a "indented code" block with ctrl-c, the entire page is copied. Copying with context menu works as expected.
