### ISSUE TITLE
<kbd> tags are ugly

### ISSUE THREAD

**Issue by IonicaBizau** [atom/markdown-preview#261]
The `<kbd>Some button</kbd>` snippets are rendered correctly, but the styling is ugly (at least I guess they are not supposed to look so, or it can be improved anyway). :smile: 

> ![image](https://cloud.githubusercontent.com/assets/2864371/8132580/64280726-112b-11e5-97fe-1f830f3aa25d.png)

I'm using the dark theme.

**Comment by simurai** [comment]
@IonicaBizau Which dark theme are you using? By default is should look like this:

![screen shot 2015-06-14 at 4 09 39 pm](https://cloud.githubusercontent.com/assets/378023/8147632/6150f874-12b0-11e5-824c-0b49de8e3ab2.png)

**Comment by IonicaBizau** [comment]
@simurai *One Dark* -- I guess this is the default theme.

**Comment by simurai** [comment]
That's odd, in One Dark UI, it looks like this for me:

![screen shot 2015-06-14 at 10 46 35 pm](https://cloud.githubusercontent.com/assets/378023/8148782/57918ef2-12e7-11e5-99d6-efc501e2d3b3.png)

There must be something that overrides the markdown-preview styles: https://github.com/atom/markdown-preview/blob/master/assets/primer-markdown.less#L435-L447 What's the Syntax theme?

**Comment by IonicaBizau** [comment]
@simurai *One Dark* too:

![image](https://cloud.githubusercontent.com/assets/2864371/8148826/a993ba94-12b6-11e5-8097-a711cc8a2e94.png)

Is it possible that the GTK theme can affect that? Or how can I be sure that I have the latest updates?

![image](https://cloud.githubusercontent.com/assets/2864371/8148828/d5041372-12b6-11e5-9b34-aa068e365a33.png)

**Comment by mnquintana** [comment]
@IonicaBizau Can you reproduce this in safe mode? (`atom --safe`)

**Comment by IonicaBizau** [comment]
@mnquintana Yes :thought_balloon: 

![image](https://cloud.githubusercontent.com/assets/2864371/8148840/47e9dbec-12b7-11e5-8023-b430a939d9aa.png)

**Comment by simurai** [comment]
Ha.. that's quite the mystery. If you don't mind inspecting with the DevTools, that should give some clues.

1. Menu > `View > Developer` and then `Toggle Developer Tools`
2. Click on the magnifying glass
3. and then on the `kbd` in the preview.

![screen shot 2015-06-15 at 11 02 39 am](https://cloud.githubusercontent.com/assets/378023/8151753/1c68b51e-134e-11e5-848d-8cd1abc2a3ff.png)
![screen shot 2015-06-15 at 10 59 10 am](https://cloud.githubusercontent.com/assets/378023/8151813/380891c6-134f-11e5-9fc8-8f6c8c508380.png)

On the right are all the styles getting applied to the keybinding.

**Comment by IonicaBizau** [comment]
@simurai Sure, I'm pretty comfortable with dev tools. :smile: 

![image](https://cloud.githubusercontent.com/assets/2864371/8154572/311de3d0-1344-11e5-8a16-466e8cc415ae.png)

It looks like the *One Dark* theme overrides the style:

![image](https://cloud.githubusercontent.com/assets/2864371/8154593/60a08e78-1344-11e5-9523-e738dfc42076.png)

**Comment by simurai** [comment]
Can it be that you're using an older version of Atom? Looks like the `color` is missing, but that should be fixed once you update Atom to the most recent version (`0.209.0`).

**Comment by mnquintana** [comment]
@IonicaBizau What version of Atom are you using?

**Comment by IonicaBizau** [comment]
I was using `0.192.0-ca99ff4`. After updating to the latest release the issue was fixed. Thanks!
