### ISSUE TITLE
Syntax highlighting incorrectly highlights underscores

### ISSUE THREAD

**Issue by josh-egan** [atom/markdown-preview#279]
Here's an example:

```markdown
The _layout.jade file, as well as any other _fileName.ext, will be ignored.
```

When the above markdown is compiled, it is not italicized, but the syntax highlighter incorrectly colors the text as if it were italicized.

**Comment by kevinsawicki** [comment]
I believe this is a duplicate of https://github.com/atom/language-gfm/issues/44 which affects both bold and italic decorators.
