### ISSUE TITLE
Live updating is *very* laggy

### ISSUE THREAD

**Issue by jaboutboul** [atom/markdown-preview#283]
I'm experiencing an issue where the live preview is taking a few seconds to update after each change, which is a horror to get anything useful done.

I would love to help diagnose why this is happening? Does it have anything to do with the mini-map?

Either way, I've opened this file (52k) in sublime and it has no such issues.

Thanks

**Comment by erwald** [comment]
Do you have code blocks in the markdown file? If so, this seems like a duplicate of atom/markdown-preview#197.

**Comment by jaboutboul** [comment]
Thanks. Looks like thats it indeed.
