### ISSUE TITLE
Tree-View context menu does not show

### ISSUE THREAD

**Issue by cakebake** [atom/markdown-preview#294]
Currently the context-menu does not appear in tree-view pane ... the DOM selector seems to stop working :(

Does not work for example: ```.tree-view .file .name[data-name$=\\.markdown]```

**Works**: ```.tree-view .file```

Somehow you can no longer reach the filename selector ```span``` inside ```ul > li```... I use in a package basically the same selectors and had no success.

**Comment by Galadirith** [comment]
@cakebake I've raised an issue with the `tree-view` devs https://github.com/atom/tree-view/issues/555 and they're already looking in to it :D

**Comment by saschagehlich** [comment]
It's fixed already, it just needs to be reviewed:

https://github.com/atom/tree-view/pull/556

**Comment by cakebake** [comment]
Thanks for the info :)
