### ISSUE TITLE
Make preview white background

### ISSUE THREAD

**Issue by rajohns08** [atom/markdown-preview#295]
I'd prefer if my preview had a white background instead of adhering to my dark theme. Is this possible? When I Ctrl+Shift+M it is dark by default.

**Comment by mnquintana** [comment]
It is! Try setting "Use GitHub.com style" for markdown-preview:

<img width="478" alt="settings_-__users_machistequintana_code_campus-map_-_atom" src="https://cloud.githubusercontent.com/assets/823545/9420402/3eaf5f64-4833-11e5-89d9-6cf989d00603.png">

**Comment by Sreekiranar** [comment]
Thanks a lot!!
