### ISSUE TITLE
Feature: Full window

### ISSUE THREAD

**Issue by mindware** [atom/markdown-preview#300]
Is there anyway to see the current markdown preview as a full tab instead of seeing it as a split one? Is there any "full-window" mode?

**Comment by thomasjo** [comment]
Navigate to the markdown-preview settings, and uncheck `Open Preview In Split Pane`

<img width="680" alt="settings_-__users_thomasjo_uni_-_atom" src="https://cloud.githubusercontent.com/assets/3622/9713147/c3b767be-554f-11e5-995c-b13bf77f68d2.png">

**Comment by mindware** [comment]
Thanks a lot for the response. It's great there's a setting I'm really enjoying the plugin. It would be awesome if we could use a short-cut command to go into either split plane or full window, instead of having to manually modify the settings each time.
