### ISSUE TITLE
Does not link referred links correctly

### ISSUE THREAD

**Issue by rugk** [atom/markdown-preview#305]
Because of https://github.com/slang800/atom-tidy-markdown/issues/20 I referrer linked a link in an markdown file and it was not linked correctly in the resulting HTML code. It was just linked to `1` if the code is e.g. like this:

```md
[link](1)

[1]: https://www.example.com
```

**Comment by rugk** [comment]
Okay, maybe that's the same as https://github.com/atom/markdown-preview/issues/153

If you agree you may close this issue.

**Comment by rugk** [comment]
Okay, after reading #153 again I saw that it's not exactly the same, but it's similar.
The difference is: Referring links is included in the basic markdown specification and no special feature of some implementations.

**Comment by graehu** [comment]
@rugk  Try this instead:

    [link][1]
    [1]:http://www.google.com

You need to use square braces for annotated linking.

    [link](http://www.google.com)

The syntax for inline linking uses parenthesis

**Comment by rugk** [comment]
Works. You're right that's the correct syntax.
