### ISSUE TITLE
preview function not work in Mac OSX

### ISSUE THREAD

**Issue by jtHwong** [atom/markdown-preview#308]
hello, when i use the plugin in mac, the preview function don't work.

**Comment by izuzak** [comment]
Works for me. Can you provide more information? Which version of Atom are you using, which version of OSX, can you reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode), which steps _exactly_ reproduce the problem for you? Happy to reopen if you can share more information.
