### ISSUE TITLE
Long single-line code block causes content to be cut off

### ISSUE THREAD

**Issue by mattbell87** [atom/markdown-preview#315]
I've noticed that if you have a single line of text that's too long for the window, it causes a horizontal scrollbar to appear. Because it's only a single line it appears there is not enough room to fit the vertical scrollbar, so it just causes the content to be cut off.

Tested on OSX and Ubuntu:
![screen shot 2015-10-12 at 4 09 10 pm](https://cloud.githubusercontent.com/assets/2722612/10421834/ffdb3e74-70fb-11e5-839d-8b0ebeb37b0f.png)
![screen shot 2015-10-12 at 4 18 22 pm](https://cloud.githubusercontent.com/assets/2722612/10421871/ee20a2d6-70fc-11e5-8ed4-759d7c0f31cb.png)

**Comment by mattbell87** [comment]
Just realised after some thorough searching there is already a bug filed for this:
https://github.com/atom/markdown-preview/issues/234

**Comment by izuzak** [comment]
> Just realised after some thorough searching there is already a bug filed for this:
> #234

Yep, let's keep the feedback in that issue -- closing this one. :v:
