### ISSUE TITLE
Keybinding doesn't work to toggle markdown preview

### ISSUE THREAD

**Issue by lifeiscontent** [atom/markdown-preview#321]
On Windows 10
with version 1.0.19

when trying the keymap <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>m</kbd>

this doesn't trigger the markdown preview like the docs say.

**Comment by izuzak** [comment]
Please include a screenshot of the keybinding resolver, as I asked in the other thread. Happy to reopen when you do.

https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings
