### ISSUE TITLE
Copying to clipboard no longer works

### ISSUE THREAD

**Issue by ijwilliams** [atom/markdown-preview#325]
When I select and copy formatted text from the previewer, it does not actually copy to my clipboard. This worked beautifully with Atom 1.0.19 and markdown-preview 0.150.0; however,with Atom 1.1.0 and markdown-preview 0.154.0, it does not. Confirmed on two computers.

**Comment by dmorneau** [comment]
+1 - I tried both ctrl-c and the right-click menu, but it's impossible to copy from the preview now.

**Comment by benaguilar** [comment]
This broke the main use I had for markdown preview =(. Hope it gets resolved soon.

**Comment by pixelchutes** [comment]
Also confirmed here for `atom@1.1.0`, `markdown-preview@0.154.0`.

No errors in console.

**Comment by lzyy** [comment]
confirmed for `atom@1.2.0`, `markdown-preview@0.156.0`

**Comment by focusaurus** [comment]
confirmed for `atom@1.2.4` and `markdown-preview@0.156.0`

**Comment by 50Wliu** [comment]
Should be fixed by atom/atom#9796.
