### ISSUE TITLE
Preview Not Working

### ISSUE THREAD

**Issue by mmstick** [atom/markdown-preview#347]
Pressing `Ctrl + Shift + M` or manually selecting it when editing markdown simply does nothing in Atom 1.2.4.

**Comment by mnquintana** [comment]
Hmm I can't seem to reproduce this with Atom 1.2.4 - can you reproduce this in safe mode? (`atom --safe`)

**Comment by mmstick** [comment]
It seems to be caused by the language-markdown plugin.
