### ISSUE TITLE
Save as HTML issue

### ISSUE THREAD

**Issue by secureinfo42** [atom/markdown-preview#353]
Hi, first of all, thanks for this extension that is really helpful for me.

When I want to export to HTML, the GitHub.com style is not exported, so the HTML output looks like to Atom theme.

**Comment by simurai** [comment]
This is a duplicate of https://github.com/atom/markdown-preview/issues/339.

There is already a PR for it https://github.com/atom/markdown-preview/pull/335 but still has some issues with the spec.
