### ISSUE TITLE
Not running by default keybinding 

### ISSUE THREAD

**Issue by jumbosushi** [atom/markdown-preview#354]
I'm using a Win 10 and the markdown-preview is not run when I press ctml - shift -m :/

Any idea why?

**Comment by lee-dohm** [comment]
Have you tried using the Keybinding Resolver (<kbd>Cmd+.</kbd> on OS X and <kbd>Ctrl+.</kbd> on other platforms)? It will show you what key Atom saw you press and the command that was triggered because of it.

**Comment by T1loc** [comment]
The keybinding show the correct binding, but nothing happens

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* Do you have [Emmet](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by jumbosushi** [comment]
I tried ctrl + . and was able to fix it! Turns out, emmet overrode ctrl-shift-m for their merge lines command :/. Thanks for the help!

**Comment by 50Wliu** [comment]
@jumbosushi Awesome, thanks for the update and glad you solved the issue!

**Comment by T1loc** [comment]
For me, I wasn't able to fix it. I don't have emmet and with atom --safe it's work.
So I think there are a conflicts with one of my install package

**Comment by T1loc** [comment]
Ok I problem is fix too. The package : language-markdown (burodepeper) break the keybinding.

Thank you for your debug tips.
