### ISSUE TITLE
Letter case ignored when previewing embedded image on Windows 7

### ISSUE THREAD

**Issue by mlenkeit** [atom/markdown-preview#359]
I have an image file, e.g. `sample.jpg` (that's the name as displayed by the Windows 7 file explorer). When I try to embed the image into a markdown file, each of the following syntax samples work:

```
![Sample](./sample.jpg)
![Sample](./sample.JPG)
![Sample](./SaMpLe.JpG)
```

Obviously, the letter case is ignored. I'm not too sure whether this is a problem with markdown-preview itself or it's due to the fact that I run Atom on Windows 7.

The expected behavior would be for markdown-preview to not display the image if the letter case doesn't match.

FYI, I noticed this behavior for the first time when I pushed a markdown file to a GitHub repository. There, the image was only displayed correctly if the letter case matches (I guess GitHub runs on a different OS).

- Max

**Comment by lee-dohm** [comment]
As you suspected, this is a side effect of running Atom on Windows. Windows searches for files in a case-insensitive manner by default. (You can change it, but it is hard.) Because of this, I don't think it is wise to work around what is expected behavior for the platform.

**Comment by mlenkeit** [comment]
Fair enough, thanks for clarification :+1:
