### ISSUE TITLE
Indent for markdown Table of Content preview when press "cmd + r"

### ISSUE THREAD

**Issue by gudh** [atom/markdown-preview#366]
Thanks for this amazing plugin! 

Here's my problem:

There is no indent with Atom when I use keyboard **"cmd + r"** to show the Table of Content 

![snip20160211_3](https://cloud.githubusercontent.com/assets/3378031/12972266/aa3eb2e0-d071-11e5-9fa8-ef8a684cfe0d.png)

**While Sublime Text**:

![snip20160211_2](https://cloud.githubusercontent.com/assets/3378031/12972284/c71e9a06-d071-11e5-9eaa-06584aaf0d41.png)

May I ask if it's possible to add indent?

**Comment by lee-dohm** [comment]
This actually is functionality provided by the [symbols-view package](https://github.com/atom/symbols-view). Would you mind reopening the Issue there?
