### ISSUE TITLE
Markdown preview freezes Atom if YAML frontmatter is indented

### ISSUE THREAD

**Issue by reitzig** [atom/markdown-preview#371]
This document works fine:

```Markdown
---
title: Test
---

Some text
```

But this causes Atom to freeze with 100% CPU usage:

```Markdown
---
 title: Test
---

Some text
```

Note the single-space indentation.

**Comment by 50Wliu** [comment]
I can't reproduce this on Atom 1.6.0-dev-d091a10.  Can you please try safe mode (`atom --safe`)?  Thanks.

**Comment by reitzig** [comment]
Freeze happens also with `--safe`.

I'm on 1.0.19, though. (That's the version in the Ubuntu 14.04 LTS repos. Two months until upgrade.)

**Comment by 50Wliu** [comment]
Hmm...can you please try manually updating to the latest stable Atom version, 1.5.3?

**Comment by reitzig** [comment]
Aye. Problem persists in 1.5.3, with and without `--safe`.

Do you need any additional information?

FWIW, I have markdown-preview 0.157.1 but the package manager does not find any updates.

**Comment by oivindoh** [comment]
Got the same thing here using 1.5.3 and markdown-preview 0.157.3

Started with this markdown document saved:
<img width="574" alt="screenshot 2016-02-17 20 54 13" src="https://cloud.githubusercontent.com/assets/153668/13122756/e0075994-d5b8-11e5-8a64-182aa59a6e3d.png">

Saved it and the indentation got removed by the tidy-markdown package and everything was OK. However, with the preview pane actually enabled, AtomHelper starts eating 100% cpu as soon as I add the space in front of title:

<img width="1058" alt="screenshot 2016-02-17 20 54 50" src="https://cloud.githubusercontent.com/assets/153668/13122813/348c51e0-d5b9-11e5-9376-dfd3417271e1.png">

**Comment by reitzig** [comment]
Looking at the source, it seems this may be an issue imported from gjtorikian/roaster which in turn uses nodeca/js-yaml. Actual parsing of YAML seems to be implemented [here](https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/loader.js) which has the looks of an ad-hoc parser.
 Go figure.

**Comment by lee-dohm** [comment]
I just attempted to reproduce this using Atom v1.9.9 on Mac OS X 10.11.6 and was unable to. Is this still a problem?

**Comment by reitzig** [comment]
Can not reproduce on Ubuntu 16.04 with

Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by 50Wliu** [comment]
Awesome, thanks for the update @reitzig!  Glad it works for you now.
