### ISSUE TITLE
Toggle HTML source preview?

### ISSUE THREAD

**Issue by danielbayley** [atom/markdown-preview#373]
It would be cool if we could toggle between the rendered HTML and the raw HTML, like [atom-source-preview](https://github.com/aki77/atom-source-preview) does for other languages…

**Comment by X-Raym** [comment]
👍 
This feature could be nice indeed, as for seing source code, we currently have to save/copy the HTML in a new file, which is not very "live".

Thanks for your work!

**Comment by danielbayley** [comment]
I just released [source-preview-markdown](https://atom.io/packages/source-preview-markdown) to handle this…

**Comment by X-Raym** [comment]
@danielbayley Thanks ! :)
