### ISSUE TITLE
Cannot toggle with shortcut keys

### ISSUE THREAD

**Issue by mpower02** [atom/markdown-preview#383]
Pressing Shift + Ctrl + M to try to toggle Markdown Preview panel several times and it disappears.  Also change HTML on current page.

**Comment by iawia002** [comment]
me too

**Comment by 50Wliu** [comment]
Does this happen in safe mode (`atom --safe`)?  What Atom version and OS are you using?

**Comment by iawia002** [comment]
i know the reason, it conflict with emmet

**Comment by lee-dohm** [comment]
Thanks for the update @iawia002. Since we haven't gotten a response from the original poster, I'm going to close this.

**Comment by mpower02** [comment]
Hey guys, I originally ran into this problem close to 5 months ago.  Didn't think anyone had a solution for this.

Recently updated to Atom 1.9.8 on  El Capitan version 10.11.6.  iawia002 is correct!  When I disable emmet package it works again.
