### ISSUE TITLE
Font not exported with html

### ISSUE THREAD

**Issue by Jameskmonger** [atom/markdown-preview#385]
When I save a markdown file to HTML by right clicking on the markdown preview pane and selecting "Save As HTML...", the font in the preview is not the font in the exported HTML.

This appears to be caused by `data-use-github-style` not being applied at all.

**Comment by 50Wliu** [comment]
> This appears to be caused by data-use-github-style not being applied at all.

Then that sounds like this bug should have been fixed with #335 - could you please double-check to confirm?  The bundled version of markdown-preview doesn't contain that fix yet.

**Comment by Ben3eeE** [comment]
Looks like this was solved by #335. Closing.
