### ISSUE TITLE
 Use GitHub.com style

### ISSUE THREAD

**Issue by mystrdat** [atom/markdown-preview#391]
Doesn't seem to work in the latest version 0.158.0. The preview pane stays on default skin theme, even though the checkbox is enabled. There also is a minor visual bug in the checkbox (light circle when disabled).

**Comment by mystrdat** [comment]
Well, to top it off, it crashes after roughly 10 minutes of using the preview window. Windows 10 platform.

**Comment by kevgathuku** [comment]
Hi @mystrdat I can't seem to be able to reproduce this on Atom 1.8.0 and Markdown-Preview v0.158.0.
Are you still facing this issue?

**Comment by 50Wliu** [comment]
Unable to reproduce on Windows 10 x64.

**Comment by lee-dohm** [comment]
@mystrdat Can you still reproduce this? None of us have been able to.

**Comment by kevinsmith** [comment]
I have a feeling the confusion comes from the interactive checkbox that's in the package README. Checking/unchecking that box does nothing. Scroll up to the "Settings" to see the *actual* config item.

**Comment by mystrdat** [comment]
Trying again the checkbox seems to work and correctly switch to Github preview theme, but the app still crashes shortly after.

**Comment by 50Wliu** [comment]
> but the app still crashes shortly after.

This is different from what you originally reported...does the crash still happen in safe mode (`atom --safe`)?

**Comment by xh3b4sd** [comment]
I am using Atom 1.11.1. The Github preview as being checked by default does not work. The checkbox in the settings page does also not react at all. Clicking on it does nothing. 

<img width="1440" alt="screen shot 2016-10-18 at 15 04 10" src="https://cloud.githubusercontent.com/assets/552769/19478762/1435f2b6-9544-11e6-945e-94c8a30ac7fc.png">

**Comment by 50Wliu** [comment]
> The checkbox in the settings page does also not react at all. Clicking on it does nothing.

You're not in the package settings for markdown-preview, but rather looking at its readme which happens to have a checkbox.  Scroll up to find the actual checkbox.

I definitely agree that this is confusing though: @atom/feedback should the checkbox in the readme be removed?  None of the other packages with settings have this.

**Comment by mnquintana** [comment]
Yeah, let's take out the checkbox in the readme and just put `Enable GitHub.com Style` in backticks.

**Comment by xh3b4sd** [comment]
@50Wliu oh wow. I got totally tricked by that. xD Thanks for the clarification. So the Github style rendering does work now. It is only that it has not really something to do with Github. Github renders styles, e.g. for code blocks, very differently. 

This is how the rendering looks like in Github. 

<img width="698" alt="screen shot 2016-10-18 at 17 53 46" src="https://cloud.githubusercontent.com/assets/552769/19485561/c8553330-955b-11e6-9d83-f91d781bdba7.png">

This is how the rendering looks like in Atom. 

<img width="598" alt="screen shot 2016-10-18 at 17 49 35" src="https://cloud.githubusercontent.com/assets/552769/19485480/99942c22-955b-11e6-9fd2-e60bf757d021.png">

**Comment by simurai** [comment]
> @xh3b4sd Github renders styles, e.g. for code blocks, very differently.

GitHub style code blocks still need to be implemented: https://github.com/atom/markdown-preview/issues/244.

In the meantime, if you don't mind switching themes, the GitHub syntax theme might get you close: https://atom.io/themes/github-atom-light-syntax.
