### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by KevinBurton** [atom/markdown-preview#395]
I have a file README.md. But I am not sure what to do from here. How do I invoke the application?

**Comment by 50Wliu** [comment]
Use the <kbd>Ctrl+Shift+M</kbd> keybinding to activate this package.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
