### ISSUE TITLE
Syntax highlighting doesn't work in preview if the language name is capitalized

### ISSUE THREAD

**Issue by esdoppio** [atom/markdown-preview#396]
With GitHub flavored Markdown:

    ```Ruby
    module Turbine
    end
    ```

    ```ruby
    module Turbine
    end
    ```

**Expected behavior:**

In the preview, syntax of both snippets should be highlighted accordingly.

**Observed behavior:**

In the preview, syntax of the "ruby" snippet is highlighted as expected, while there's
no highlighting for the "Ruby" snippet.

**Atom version:** 1.7.3
**OS and version:** OS X 10.11.5

**Installed packages:**

* **markdown-preview:** 0.158.0

**Additional information:**

* Problem can be reliably reproduced, doesn't happen randomly:Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by 50Wliu** [comment]
Fixed by #398.
