### ISSUE TITLE
Links with unicode characters?

### ISSUE THREAD

**Issue by BurningLutz** [atom/markdown-preview#400]
Seems that the generating of `id` for a header with unicode characters such as `你好` is not correct, it simply generated a `-` for the id. So clicking on a link to that header will fail to jump to the correct position.

Sample:

``` md
[你好](#你好) // Clicking on this link takes no effect.

# 你好
```

**Comment by esdoppio** [comment]
Probably caused by https://github.com/chjj/marked/blob/master/lib/marked.js#L800

**Comment by esdoppio** [comment]
And someone has already opened a [PR](https://github.com/chjj/marked/pull/436/files) for this.
