### ISSUE TITLE
Warn on Keybinding overwrite

### ISSUE THREAD

**Issue by kevgathuku** [atom/markdown-preview#409]
Hi, 
I have been using Markdown preview and I am loving it. 

However,  there are some packages that could potentially override the `ctrl-shift-m` Keybinding used by Markdown Preview. 
For example, I installed [emmet](https://github.com/emmetio/emmet-atom) which uses the same Keybinding, and therefore overrides the Markdown preview Keybinding. 

Would it be possible to warn the user in such instances, where a package they are installing could override this package's Keybinding?

**Comment by ahmad2smile** [comment]
Do you know how to solve it then ? As I don't wanna remove Emmet.

**Comment by kevgathuku** [comment]
@ahmad2smile I had to remove emmet as I wasn't using it at the time. I haven't found a solution yet.

**Comment by ahmad2smile** [comment]
Custom Key Binding ?? Like 
 'markdown-preview':
   'ctrl-shift-p': 'markdown-preview:toggle'

I tried this in keymap.cson file but Its not working.

**Comment by kevgathuku** [comment]
`ctrl-shift-p` should work but your would be overriding an inbuilt keybinding

<img width="795" alt="screen shot 2016-07-25 at 9 43 58 am" src="https://cloud.githubusercontent.com/assets/3721994/17092613/88f26156-524c-11e6-9292-400242e51aa0.png">

You can check your keybindings in the settings to find if a keybinding is already in use or not.
But using a custom key binding seems to be the only solution for now. 
I have tried using `ctrl-shift-q` and it worked. This is my entry in the `keymap.cson` file
```cson
'atom-workspace':
  'ctrl-shift-Q': 'markdown-preview:toggle'
```

**Comment by ahmad2smile** [comment]
Perfect. Now Its working for me .. There is a conflict with Emmet Ctrl-Shift-M Merge Lines command so I changed It with Ctrl-Shift-Q ... Thanks Man!!

**Comment by lee-dohm** [comment]
This isn't something that would be up to the markdown-preview package. This would be something that would need to be implemented as part of https://github.com/atom/atom-keymap. Would you mind reopening your Issue there?

**Comment by kevgathuku** [comment]
@lee-dohm sure. I'll open the issue in the new repo
