### ISSUE TITLE
Code highlighting problem in Preview？

### ISSUE THREAD

**Issue by hyiihy** [atom/markdown-preview#411]
I can see the code highlighting in source but it does work on Preview view

**Comment by 50Wliu** [comment]
Can you please upload an image that shows what you're talking about?  Also, what Atom version are you using, and can you reproduce the issue in safe mode(`atom --safe`)?

**Comment by hyiihy** [comment]
Thanks for your reply.
My Atom version is 1.2.4 ,
![](https://raw.githubusercontent.com/hyiihy/MyNote/master/QQ%E5%9B%BE%E7%89%8720160804083615.png)
Its really strange that I see the highlighting in Preview view when in safe mode but not in source view. It just contrary to what I see in a ordinary model.
safe model:
![](https://raw.githubusercontent.com/hyiihy/MyNote/master/QQ%E5%9B%BE%E7%89%8720160804083647.png)
ordinary model:
![](https://raw.githubusercontent.com/hyiihy/MyNote/master/QQ%E5%9B%BE%E7%89%8720160804083651.png)

**Comment by 50Wliu** [comment]
Ok, two things.
1. Your Atom version is incredibly outdated - the current version is 1.9.0.  Please update as soon as possible.
2. If it works in safe mode, that means one of your packages is breaking the highlighting.  Try using the [package-cop](https://atom.io/packages/package-cop) package to figure out which one it is.
***
1. 最新的Atom版是1.9.0 - 请您用最快的速度更新。
2. 如果用safe mode没问题，那说明您装的一个“package”出了问题。您可以用[package-cop](https://atom.io/packages/package-cop)来查出是哪个package。
