### ISSUE TITLE
Fenced code blocks are being rendered with a taller-than-necessary box

### ISSUE THREAD

**Issue by lee-dohm** [atom/markdown-preview#421]
Reproduced using Atom v1.12.0-dev-fedf783 on Mac OS X 10.11.6
## Repro Steps
1. Launch Atom in your local Atom repository
2. Create a new file using <kbd>Cmd+N</kbd>
3. Change the grammar to "GitHub Markdown" using the Grammar Selector
4. Copy the text from [this Gist](https://gist.githubusercontent.com/lee-dohm/5810159cf2b70293ca363e469d0ca395/raw/e319efd3777025263ccda097c4d2ebff0d6d4c10/test.txt) and paste it into the file
5. Open the Markdown Preview using <kbd>Ctrl+Shift+M</kbd>

**Expected:** The box around the text `Blah blah blah` to only be as short as possible
**Actual:** The box is as tall as the screen

Additionally, you can do the following after the steps above:
1. With the Markdown Preview still open, navigate to the bottom of the file using <kbd>Cmd+Down</kbd>
2. Type `testing` and press <kbd>Enter</kbd>
3. Note how the code block is still as tall as the screen in the Markdown Preview and the word `testing` is beneath it

**Comment by AndreaGriffiths11** [comment]
I was able to reproduce the issue using Atom v1.13.0 on Mac OS X 10.12.2. Thanks you @lee-dohm.

**Comment by iolsen** [comment]
<img width="612" alt="screen shot 2017-01-30 at 9 41 24 am" src="https://cloud.githubusercontent.com/assets/553742/22434293/517f4b58-e6d0-11e6-941a-fa60be0f4fc9.png">

This is what I'm seeing in 1.13.1 and 1.14.0-beta0. Taller than necessary but not as tall as the screen. MacOS 10.12.1.

**Comment by lee-dohm** [comment]
@iolsen That's what I'm getting also, even with `editor.scrollPastEnd` enabled.

**Comment by Ben3eeE** [comment]
Same results as @iolsen when I tested. Checking it off in the tracking issue.
