### ISSUE TITLE
Link with some bold words are not rendered properly

### ISSUE THREAD

**Issue by brightknight08** [atom/markdown-preview#429]
## bug description

having bold letters `[inside a **link**]` produces weird formatting
## how to reproduce

`[Wikipedia entry about **Characters per line**](https://en.wikipedia.org/wiki/
Characters_per_line "Characters per line")`
## what was expected

something like this: [Wikipedia entry about **Characters per line**](https://en.wikipedia.org/wiki/
Characters_per_line)
## system details
- atom 1.10.0
- win 10

**Comment by midhruvjaink** [comment]
Hey @brightknight08 
try this snippet - 
```markdown
[Wikipedia entry about **Characters per line**](https://en.wikipedia.org/wiki/Characters_per_line)
```
It will produce the required output -
[Wikipedia entry about **Characters per line**](https://en.wikipedia.org/wiki/Characters_per_line)
