### ISSUE TITLE
Add "Save as HTML" to Command Palette

### ISSUE THREAD

**Issue by andrewjli** [atom/markdown-preview#432]
As the title says, I think it would be a useful feature to add a `Save as HTML` option to the Command Palette (<kbd>Ctrl</kbd>/<kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>). I actually spent over an hour today trying to figure out where the `Save as HTML` was hidden. I eventually found it in the context menu of the preview panel.

Because there is a `Copy Html` option easily accessible via the command palette, my intuition lead me to believe the command should be accessible via the command palette, which clearly wasn't the case. I found it unintuitive to have to right-click on the Preview window in order to find the option.

![screen shot 2016-09-19 at 6 26 26 pm](https://cloud.githubusercontent.com/assets/8610177/18629212/add05a52-7e96-11e6-9c5b-67c5cf32f359.png)

Clearly [I'm not the only person](https://github.com/atom/markdown-preview/pull/205#issuecomment-142918373) who struggled to find this useful feature.

**Comment by 50Wliu** [comment]
In the meantime, just searching for `Save As` should do the same thing.

**Comment by billglover** [comment]
I might have a crack at this.
