### ISSUE TITLE
Preview Location Movement

### ISSUE THREAD

**Issue by bvoelker** [atom/markdown-preview#449]
In markdowns that are a bit larger than the screen height the preview jumps to another location. Kind of difficult to see your changes when the preview keeps moving.

**Comment by Joao-M-Almeida** [comment]
I have the same issue, it happens to me when saving the document and when I'm scrolled to the end on the Preview.

**Comment by Joao-M-Almeida** [comment]
I think this is the same issue as #370

**Comment by 50Wliu** [comment]
Thanks @Joao-M-Almeida, closing in favor of #370.
