### ISSUE TITLE
Markdown Checklists Aren't rendered.

### ISSUE THREAD

**Issue by chamunks** [atom/markdown-preview#450]
- [ ] Fix Checklists
- [x] Report markdown checklist rendering not working.
- [x] Supply screenshot of it not working.
![http://i.imgur.com/ZoN1O8N.png](http://i.imgur.com/ZoN1O8N.png)

**Comment by 50Wliu** [comment]
Hi @chamunks, is this reproducible in safe mode (`atom --safe`)?  If so, can you paste the output of `atom --version` here?  Thanks!

**Comment by chamunks** [comment]
Seems to work fine with "atom --safe" so it's likely an incompatibility with something else I have.  
![http://i.imgur.com/rlf4ict.png](http://i.imgur.com/rlf4ict.png)

```
⇒  atom --version
Atom    : 1.12.5
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by 50Wliu** [comment]
Ok.  If it works in safe mode you can try using the [package-cop](https://atom.io/packages/package-cop) package to track down the offending community package.

**Comment by chamunks** [comment]
Ah thanks very much I never would have looked for that otherwise.
