### ISSUE TITLE
Crash with 1.12.7 / Mac Sierra

### ISSUE THREAD

**Issue by iamcam** [atom/markdown-preview#452]
Atom crashes - as it does here https://github.com/atom/atom/issues/13308 

I verified it was this package by removing all packages and restarting Atom with each added one-by-one. Markdown-Preview was the only one that crashes Atom.

**Comment by 50Wliu** [comment]
markdown-preview shouldn't be able to be removed as it's a core package.  What's the output of `apm list --installed`?

**Comment by iamcam** [comment]
Right - I went through the filesystem route.

```
├── json-converter@0.2.4
├── json-generator@0.1.15
├── language-swift@0.5.0
├── linter@1.11.18
├── linter-jsonlint@1.3.0
├── linter-xmllint@1.4.0
├── pretty-json@1.6.1
└── swift-debugger@0.1.2
```

What's strange is that now I'm able to move the package directory back in, start Atom and it boots - now giving me options to upgrade in the package manager. After update it seems to work again. Not sure what happened there, but it was 100% reproducible.

```
├── json-converter@0.2.4
├── json-generator@0.1.15
├── language-swift@0.5.0
├── linter@1.11.18
├── linter-jsonlint@1.3.0
├── linter-xmllint@1.4.0
├── markdown-preview@0.159.1
├── pretty-json@1.6.1
└── swift-debugger@0.1.2
```
