### ISSUE TITLE
Importing Google fonts causes 'Content Security Policy Error'

### ISSUE THREAD

**Issue by bassdeveloper** [atom/markdown-preview#454]
![image](https://cloud.githubusercontent.com/assets/9164582/21150661/c8e68f50-c185-11e6-8ca2-a0dfdfdf9fc1.png)

I imported Google Fonts in the ```styles.less``` file. 
```less
@import url('https://fonts.googleapis.com/css?family=Open+Sans');
@import url("https://fonts.googleapis.com/css?family=Roboto+Slab|Open+Sans:400italic,700italic,400,700");
@import url("https://fonts.googleapis.com/css?family=Alegreya+Sans+SC:400,500i|Arima+Madurai:400,500");
```
Can this be only solved by downloading the fonts or can there be a workaround in the code?

If any other information is needed, please reply.

**Comment by 50Wliu** [comment]
This doesn't look like it has anything to do with Markdown Preview - please correct me if I'm wrong (preferably by showing a Markdown file with those imports).
