### ISSUE TITLE
<script> tag in markdown file getting stripped from Preview and Save As

### ISSUE THREAD

**Issue by brainlid** [atom/markdown-preview#466]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Embedded scripts in a markdown file are blocked/prevented from running in the preview.

### Steps to Reproduce

1. In a markdown file, add content like this...

```html
<script>
  console.log("Script section executed");
</script>
```

2. Open the Atom developer pane
3. Open the Markdown preview
4. See that the message is not logged

**Expected behavior:**

Some way to execute a script that is defined in a markdown file.

**Actual behavior:** 

I presume the script is blocked or stripped out during render.

### Versions

1.13.1

### Additional Information

Perhaps there is a better way to achieve may goal. I'd like to have a markdown file with nested bulleted lists. I'd like to attach an event handler to the rendered `<li>` element so I can toggle it and collapse/expand the child contents.

Using the atom editor, I can collapse/expand the markdown nested sections, but I have no way to do that on the rendered view. 

Is there a way to control the layout used when saving to HTML? Then I could inject a JS file in the layout headers. I can't find any way to do that.

**Comment by 50Wliu** [comment]
script tags are not supported by GFM (in fact, the contents are [explicitly removed](https://github.com/jch/html-pipeline/blob/419436767dce642a03fa719cc1c75e23d174861b/lib/html/pipeline/sanitization_filter.rb#L50)).  So I'm going to close this as `wontfix`.
