### ISSUE TITLE
I have the package enabled but unable to use the shortcut to view a preview.

### ISSUE THREAD

**Issue by VictoriaVasys** [atom/markdown-preview#475]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Hi @VictoriaVasys :wave: - can you edit the post and fill in all the details asked for in the issue template?

**Comment by stuartjnelson** [comment]
@rsese I'm unable to open the preview window.

I've tried using the default key bindings as well as custom key mapping. I'm using a file with extension `.md`

**Version**
```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
markdown-preview :0.159.6
```

**Comment by rsese** [comment]
Hmmm, what does the [keybinding resolver](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-your-keybindings) show you when you try to toggle Markdown preview @stuartjnelson?

Also, are you able to use the command palette to toggle the preview?

**Comment by stuartjnelson** [comment]
I have `Emmet 2.4.3` installed. This has a command for merging lines for the same keybinding. I unset this and then reset it in my `keymap.cson` and it works! Sorry this was a dumb mistake. Thanks for taking the time to help me out. Love the plugin!

**Comment by rsese** [comment]
Glad you have things sorted out @stuartjnelson :v:

I'll go ahead and close this for now @VictoriaVasys but if you have steps to reproduce, please let us know and we'll take a look.
