### ISSUE TITLE
Markdown preview doesn't escape the `#` character properly when used in a header

### ISSUE THREAD

**Issue by mesaugat** [atom/markdown-preview#481]
### Prerequisites

* [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [x] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
* [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Markdown preview doesn't escape the `#` character properly when used in a header

### Steps to Reproduce

1. `## Y - \#` renders as `Y - ` 
2. `## Something \##` renders as `Something \`

**Expected behavior:**

1. Should render: `Y - #`
2. Should render: `Something ##`

**Actual behavior:** Same as expected behaviour

**Reproduces how often:** 100%

### Versions

Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.12.2

**Comment by pbteja1998** [comment]
I want to take this issue, can someone guide me how to get started?
