### ISSUE TITLE
Super and sub script preview

### ISSUE THREAD

**Issue by barrust** [atom/markdown-preview#487]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The markdown preview does not currently adhere to the github markdown for superscript (x^2) and subscript tags. It would be helpful if the preview showed rendered these. 

### Steps to Reproduce

1. Attempt to add a superscript tag to a *.md file
2. Use the Packages->Markdown Preview to review the markdown file
3. Ensure superscript tag is rendered as superscript

**Expected behavior:** Expect to see the text in superscript

**Actual behavior:** Renders the text verbatim while it works on the github site

**Reproduces how often:** 100%

### Versions

Linux: Elementary OS 0.4.1  
Atom 1.17.2

### Additional Information

N/A

**Comment by barrust** [comment]
This works in preview when using the "Use Github.com style" option. 
markdown-preview version: 0.159.12

**Comment by liawagner** [comment]
For me it is *not* working in preview when using the "Use Github.com style" option.

markdown-preview version: v0.159.20

**Comment by barrust** [comment]
closing
