### ISSUE TITLE
Provide proper highlighting in editor

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [atom/markdown-preview#490]
Compare how the same markdown looks in sublime and atom:

Sublime Markdown GFM:
![1](https://user-images.githubusercontent.com/6263572/27176532-cf31666c-51ba-11e7-9fe7-7a240070e0a8.png)

Atom:
![2](https://user-images.githubusercontent.com/6263572/27176538-d45c5eb2-51ba-11e7-845e-bad5b1c399b8.png)

In atom highlighting is only shown in the final generated document. So you can't get a feel of the document's structure when you're editing it.

Yes I know I can generate the preview with a hotkey but nothing will provide faster feedback than having highlighting in the editor. That boosts the productivity quite a lot.

Please consider this feature request for future releases.

Thanks

**Comment by rsese** [comment]
Thanks for the report!

I wonder if this is a syntax theme issue?  This is what I see with One Light:

![one-light-gfm](https://github-slack.s3.amazonaws.com/monosnap/test.md__sandboxtmp_2017-06-15_14-23-25.png)

But in Atom Light I see the same thing as you:

![atom-light-gfm](https://github-slack.s3.amazonaws.com/monosnap/test.md__sandboxtmp_2017-06-15_14-24-42.png)

Are you using Atom Light as your syntax theme @Kshitiz-Sharma?

**Comment by rsese** [comment]
If you can confirm, we should move this to https://github.com/atom/atom-light-syntax if there isn't an already existing issue.

**Comment by 50Wliu** [comment]
Correct, this is a syntax theme issue.  Bold/italics have separate markup styles that syntax themes can target.

**Comment by Kshitiz-Sharma** [comment]
@rsese @50Wliu 

Yes I am using Atom Light. You can move this to the theme repo although I'm not sure if it can be fixed there properly. Because themes are generic and to do proper highlighting would require interpretation of the document structure. For example, the plugin should be able to recognise a code block and set a light gray background color for that block to distinguish it from non-code text. Or provide a different font size for different heading levels.

With One Light theme I see colors change but highlighting seems to be generic. It seems to make all text starting with # red color. There is no recognisation of heading level etc.

What are your thoughts?

**Comment by 50Wliu** [comment]
@Kshitiz-Sharma what you're asking for is all possible, with the exception of different font sizes (Atom currently assumes a single font size).  Each heading level has different scopes, code blocks have specific meta scopes that can be targeted, etc.

Therefore I'm going to close this issue - please open an issue on one-light-syntax instead asking for improved Markdown highlighting.
