### ISSUE TITLE
TextEditors generated from fenced code blocks are editable

### ISSUE THREAD

**Issue by BinaryMuse** [atom/markdown-preview#491]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The markdown-preview window renders fenced code blocks as editable TextEditors

### Steps to Reproduce

1. Add a fenced code block to a markdown file
2. Preview the file with markdown preview

**Expected behavior:** [What you expect to happen]

The TextEditors generated from the fenced code blocks are read-only

**Actual behavior:** [What actually happens]

The TextEditors generated from the fenced code blocks are editable

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Atom    : 1.20.0-dev-6ab89cfb2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by chibicode** [comment]
This might be related, but if you select text, it seems to move the text around.

![](https://cl.ly/3o3S2z1F1C2y/Screen%20Recording%202017-08-13%20at%2002.40%20PM.gif)

Atom: 1.19.0 
markdown-preview: 0.159.12
