### ISSUE TITLE
List checkbox preview incorrect :(

### ISSUE THREAD

**Issue by axklim** [atom/markdown-preview#497]
OC: windows 10

Incorect:
![bug_chekbox](https://user-images.githubusercontent.com/12901433/30027046-ec7f4de4-9187-11e7-8340-e97bdcc27c5e.png)

Normal:
![chekbox](https://user-images.githubusercontent.com/12901433/30027047-ec81a4ea-9187-11e7-9df6-c7cf8a7321d7.png)

**Comment by thomasjo** [comment]
Duplicate of #282
