### ISSUE TITLE
Last plantuml graph overwrites all others in the preview of a single document

### ISSUE THREAD

**Issue by qwc** [atom/markdown-preview#499]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When you write a document with multiple plantuml graphs inside all graphs are overwritten with the last one defined in the document.

### Steps to Reproduce

1. Write a document like the following
> \# testdocument
> first diagram/graph:
> \`\`\`puml
> @startuml
> actor test
> @enduml
> \`\`\`
> second diagram/graph
> \`\`\`puml
> @startuml
> node anothertest
> @enduml
> \`\`\`

2. Watch while typing or copying parts of the document, how the graph is generated in the preview
3. first the actor test is shown
4. then a second graph appears and both have the content with the node "anothertest"

**Expected behavior:** 
I expect that I can write multiple graphs in any graph language in one document (if thats plantuml or whatever, doesnt matter).

**Actual behavior:** 
When you write more than one plantuml graph, all graphs are overwritten with the last defined one.
**Reproduces how often:** 
always.

### Versions
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4

Ubuntu 16.04

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
@qwc are you sure you tested this in safe mode?  markdown-preview doesn't handle PlantUML graphs.

**Comment by qwc** [comment]
Uh, wait a second? Did I click the wrong project link? I was using markdown-preview-enhanced.

OMFG, I really got to the wrong project, I'm sorry, just delete it, this project doesn't have anything to the issue. ... How embarrassing... :/

**Comment by 50Wliu** [comment]
No problem at all :grinning:

Happens to everyone once in a while.
