### ISSUE TITLE
Bug: Image previews doesn't work

### ISSUE THREAD

**Issue by lanceplaine** [atom/markdown-preview#508]
### Description

Bug: Image previews doesn't work

<img width="1222" alt="screen shot 2017-10-26 at 9 57 39 am" src="https://user-images.githubusercontent.com/5476205/32066320-35850040-ba34-11e7-8175-4d58f9735010.png">

### Steps to Reproduce

  - Open a file with a picture

**Expected behavior:** Be able to preview the picture

**Actual behavior:** Image previews doesn't work

**Reproduces how often:** 100% of the time

### Versions

Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.5

macOS 10.13 (17A405)

**Comment by 50Wliu** [comment]
Fixed in #506.

**Comment by lanceplaine** [comment]
Thanks @50Wliu 

When can I expect this to be released?

**Comment by Ben3eeE** [comment]
Is it currently scheduled to be fixed in the next hotfix release.
