### ISSUE TITLE
problem of image show

### ISSUE THREAD

**Issue by lbing9002** [atom/markdown-preview#514]
i want to paste an image to .md file use markdown-img-paste plugin, but it cant show properly.
does anyone encountered this problem, how to fix it?
thx : )

load it in .md file:
![image1](https://user-images.githubusercontent.com/18423208/32132545-04cdc46c-bbf8-11e7-9821-f85e6639dd1a.png)

it shows like this:
![image](https://user-images.githubusercontent.com/18423208/32132654-3a6d89f2-bbfa-11e7-82c5-847e65877ee8.png)

**Comment by 50Wliu** [comment]
Should be fixed with #506.

**Comment by lbing9002** [comment]
Thanks a lot @50Wliu .
Looking forward to the next release.
