### ISSUE TITLE
Strikethroughs don't properly render for multiple lines

### ISSUE THREAD

**Issue by woolgathering** [atom/markdown-preview#518]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Strikethroughs don't properly render when the line that is to the struck wraps in the pane.

### Steps to Reproduce

1. Create a long string and strikethrough using ~~ on either end.
2. Open Markdown Preview and preview the file.
3. Shrink the preview pane until the line wraps.

**Expected behavior:** 
The strikethrough should continue through a wrapped line in a pane.

**Actual behavior:**
The strikethrough splits the distance between however many wraps are needed to show the line.

**Reproduces how often:** 
100%

### Versions

user@RAM:~$ atom --version
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

user@RAM:~$ apm --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.11.0

user@RAM:~$ uname -a
Linux RAM 4.10.0-37-generic #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Additional Information

Should be straightforward to reproduce. Not a major issue, more of an FYI.

![2017-10-29-171126_1920x1080_scrot](https://user-images.githubusercontent.com/10873395/32150275-f2c7e1cc-bccd-11e7-85a0-8a2ef3290395.png)

**Comment by rsese** [comment]
Thanks for the report!  I was unable to reproduce with Atom 1.21.1 on Ubuntu 16.04.  I just tried with this text:

```
~~hello world hello world hello world hello world hello world hello world hello world~~
```

![md-preview-strikethrough](https://user-images.githubusercontent.com/734194/32302968-a460b280-bf33-11e7-9ee3-2ff55d876f05.gif)

Let me know if I mis-understood anything.

**Comment by woolgathering** [comment]
Uninstalled and reinstalled everything. Things seem to be working now... strange.
