### ISSUE TITLE
URL comment in styles file 404s

### ISSUE THREAD

**Issue by fjwldap** [atom/markdown-preview#519]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In file "markdown-preview/styles/markdown-preview-github.less", line 13 there are URL.
But I can't find this site. 

### Steps to Reproduce

**Expected behavior:** can go to site "https://github.com/primer/markdown/blob/master/components/markdown.scss"

**Actual behavior:** Instead, this screen showed up.
![default](https://user-images.githubusercontent.com/28581665/32977031-30f1745a-cc68-11e7-84bf-9f8e9c37e770.JPG)

**Reproduces how often:** everytime..

**Comment by nineway** [comment]
If you follow the link and remove some parts at the end, you end up here https://github.com/primer/primer-markdown/, which says that the repository is deprecated and has moved to https://github.com/primer/primer. I guess that the correct source would be https://github.com/primer/primer/blob/454a8841469de50df97daf70e3cee370443a7d0f/modules/primer-markdown/lib/markdown-body.scss.

Is this correct?

**Comment by 50Wliu** [comment]
@nineway Yes, I believe that's correct.  Though I think it would be safer to link to https://github.com/primer/primer/tree/master/modules/primer-markdown, as the Markdown CSS was broken down into multiple different files.
