### ISSUE TITLE
Specify an alternative library for rendering Markdown

### ISSUE THREAD

**Issue by RedHatter** [atom/markdown-preview#523]
I believe markdonw-preview uses marked to render the Markdown. Any way to have a configuration option to choose a different Markdown parser?

**Comment by 50Wliu** [comment]
We're going to stick to one renderer so as not to overcomplicate the code.  If you'd like to use a different Markdown parser, I would encourage you to fork this package and implement it as a separate package.

Thanks for your interest in Atom!
