### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by migkapa** [atom/markdown-preview#536]
You have the core package "markdown-preview" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (<embedded>:13400:20)
Generator.next (null:null:null)
step (<embedded>:13387:279)
<unknown> (null:null:null)
process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by Arcanemagus** [comment]
Thank you for the report!

The README linked in the report gives you instructions on the steps you need to take to get rid off this deprecation https://github.com/atom/dalek#i-got-a-warning-what-do-i-do

**Comment by burak-yildizoz** [comment]
For those who are coming from [Previewing Markdown Failed](https://github.com/atom/markdown-preview/issues/579#issuecomment-705827134), using `markdown-preview-plus` as [suggested here](https://github.com/atom/markdown-preview/issues/579#issuecomment-731472497) with the latest version of Atom solved my problem.
