### ISSUE TITLE
Email inside of inline code tags (`) is incorrectly formatted

### ISSUE THREAD

**Issue by droberts-ada** [atom/markdown-preview#543]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Inline code tags surrounding an email address render incorrectly. For example, 

```
`name@example.com`
```

renders without code formatting, displays both backticks, and is a link:

![image](https://user-images.githubusercontent.com/21064499/42913678-06761422-8aab-11e8-8d83-677f44403122.png)

### Steps to Reproduce

1. Create a markdown file, `test.md`, and open it in Atom
2. Type `` `name@example.com` ``
3. Save the file
4. Open the markdown preview

**Expected behavior:** Should render "name@example.com", as code, no link

**Actual behavior:** Renders without code formatting, displays both backticks, and is a link:

![image](https://user-images.githubusercontent.com/21064499/42913678-06761422-8aab-11e8-8d83-677f44403122.png)

**Reproduces how often:** 100%

### Versions

```
$ atom --version
Atom    : 1.28.2
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.2
python 2.7.10
git 2.17.0
```

OSX 10.11.6

**Comment by rsese** [comment]
Thanks for the report!  I can reproduce on macOS 10.12.6 with `1.30.0-nightly9` but this looks like an issue with the Markdown renderer: https://github.com/markedjs/marked/issues/1218.

**Comment by rafeca** [comment]
We've recently [upgraded the version of the markdown renderer](https://github.com/atom/markdown-preview/pull/559) and I've verified that this issue got solved! 🎉

Thanks for reporting!
