### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by DutchPete** [atom/markdown-preview#575]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I installed the markdown-preview package in Atom via the Preferences, and used the "install" button. I want to uninstall it but there is no such button. Please advise.

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

### Versions

Atom version 1.41.0, apm version 2.4.3, macOS 10.14.6 Mojave

**Comment by calebmeyer** [comment]
Hi @DutchPete. You can uninstall a package in atom in one of two ways:
In the GUI, you can uninstall a package by searching for it in the packages tab of the settings, there should be an uninstall button there:
https://flight-manual.atom.io/using-atom/sections/atom-packages/#package-settings

At the command line, atom ships a CLI tool called `apm`, the atom package manager. You can `apm install <package-name>` and then later `apm uninstall <package-name>`:
https://github.com/atom/apm#installing

**Comment by calebmeyer** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
