### ISSUE TITLE
Need ability to actually SAVE the generated HTML.

### ISSUE THREAD

**Issue by jlblank** [atom/markdown-preview#58]
markdown-preview:show is great, but there seems to be no way to actually save the HTML it generates... just to view it in the preview pane (which is highly useful, but only half the story).

A markdown-preview:SaveAsHTML or something would be nice.

I tried clicking in the preview tab to put the focus on it, then going File > Save As. It doesn't work; literally nothing happens. I didn't get a save dialogue at all.

Version is 0.83.0.

**Comment by MGaetan89** [comment]
It would be nice to also include `<meta charset="utf-8">` in the generated HTML.
