### ISSUE TITLE
Should markdown preview adhere to your theme?

### ISSUE THREAD

**Issue by benogle** [atom/markdown-preview#6]
Right now, it looks like github's website (syntax and all!), no matter the themes you have activated. 

Do you think it should adhere to your current theme? 

If so, I was thinking I could extract the current styles into a github-markdown-theme package so people could make it look like the website.

**Comment by alexrussell** [comment]
I feel I must point out that while markdown-preview adhering to your currently-select theme is pretty great for the actual purpose of the plugin (previewing markdown files), I feel that when the HTML is exported, it should default to the more standard Github-style white background, etc.

I tend to write my documentation/specs in markdown, then use markdown-preview to export HTML and then print that using Chrome*. I don't really want my current theme's styes in my printed version.

However, I do recognise that maybe markdown-preview has one goal in mind: to help you **preview** your markdown. Exporting/printing should maybe be handled by some other renderer, and 'copy/save to HTML' was only added as a convenience to people.


\* Printing directly in Atom would be great but that's an issue for another time!

**Comment by bucaran** [comment]
I think it should not, or at least there should be a way to turn this off. A markdown preview with a dark background forces me to change the theme every time I am editing markdown files.

**Comment by thomasjo** [comment]
I just need to find time to finalize https://github.com/atom/markdown-preview/pull/240. That PR resolves this issue. Feel free to test out that PR and see if it's satisfactory.

**Comment by alexrussell** [comment]
@thomasjo I have not tested the PR but it looks to me from the description and a brief look at the code that that's exactly what I'm looking for personally. Wait wait to see it merged.

**Comment by AhemNason** [comment]
I think it would be great if I could just point the preview at a custom css if I wanted so it could look like whatever I want. I use markdown for basically everything and I've been using Marked a lot, but I think it would be great to have the preview look exactly like where you're expecting the content to go, even if that's not what your editor looks like while you're working.

**Comment by kevinsawicki** [comment]
Closing this out, this feels addressed by #240, being able to override these in your `~/.atom/styles.less`, and by markdown preview now using `<atom-text-editor>` elements to render code blocks.
