### ISSUE TITLE
Panel should be resizeable

### ISSUE THREAD

**Issue by wfalkwallace** [atom/markdown-preview#62]
currently in `markdown preview: show`, the preview panel isn't resizeable.

**Comment by JackBetbeze** [comment]
Just started using atom, trying to make my first package where a panel opens to the right and I need it to be resizable. Looks like this has been an issue for the past 2 years and still hasn't gotten fixed...

**Comment by 50Wliu** [comment]
@JackBetbeze panels should be resizable - at least I've been able to resize Markdown Preview and the old Tree View for as long as I can remember.  However, you should also see if [Docks](http://blog.atom.io/2017/05/23/docks-deep-dive.html) would be a better fit than panels.
