### ISSUE TITLE
Export CSS with HTML

### ISSUE THREAD

**Issue by BlackWolf** [atom/markdown-preview#70]
Syntax themes can style the markdown preview using the `.markdown-preview` selector. I think when exporting a markdown preview to HTML, the necessary CSS to make the HTML file look the same as in atom should be embedded into the HTML.

This is especially true since one of the great benefits of markdown is that it can be so easily parsed and exported to different styles and formats - atom should make use of that power in my opinion.

**Comment by anderskaplan** [comment]
+1

**Comment by russ4stall** [comment]
+1

**Comment by mig42** [comment]
+1 :stuck_out_tongue:

**Comment by ArnaudRinquin** [comment]
Ditto this, :+1: and thanks @jrop.

**Comment by thedaniel** [comment]
#205 adds CSS to "save as HTML", and "copy as HTML" is left as the simple markup.

**Comment by graehu** [comment]
This appears to save using the wrong CSS at the moment. If you have "Use GitHub.com style" ticked in the settings, it'll still use the CSS associated with your syntax theme.

**Comment by sbojarovski** [comment]
I'm having the same problem as graehu. Maybe there is another issue for that?

**Comment by powerqian** [comment]
@graehu @sbojarovski Having the same issue here. It looks like there's a PR already (#335) but not yet merged.

**Comment by nateGeorge** [comment]
[Markdown preview plus](https://atom.io/packages/markdown-preview-plus) seems to kind of do this, but not perfectly.  I still haven't found anything that will render the html exactly the same in a browser as it looks in the preview pane in Atom.
