### ISSUE TITLE
preview pushes text into gutter

### ISSUE THREAD

**Issue by maxheld83** [atom/markdown-preview#92]
After some writing, atom pushes the first (couple of) letter(s) of my source into the gutter. This appears to happen while running `markdown-preview`. `Toggle` on / off solves the issue (see gif.).

![md-bug](https://cloud.githubusercontent.com/assets/5372770/3272150/2d7df9e0-f315-11e3-995f-672299ecf74c.gif)

My config:
- Atom 0.103.0
- Markdown Preview 0.74.0
- gif see above
- Mac OS X 10.9.3.
- maybe of note, I set `Soft Wrap` and `Soft Wrap At Preferred Line Length`, with default `80` value.

**Comment by kevinsawicki** [comment]
A lot has changed in the last year and we've haven't seen other reports of this in awhile so I'm going to close it out for now. Please comment if you still see it happening on Atom 1.0+
