### ISSUE TITLE
autocomplete image insertion, with preview

### ISSUE THREAD

**Issue by maxheld83** [atom/markdown-preview#94]
including images in markdown is kind of a chore.
I'd love it if
- [ ] atom could autocomplete filenames (URLs, actually) for images in the same repository (or project folder).
- [ ] a little (inline) preview of the image, in case the filename is not instructive (as is unfortunately often is).

I'm not sure this package would even be the right place for this feature, but I thought it couldn't hurt to ask.

- This is a duplicate of atom/image-view#24.
- Also raised this as a [discussion post](http://discuss.atom.io/t/package-for-image-autocompletion-preview/10211)

**Comment by kevinsawicki** [comment]
This isn't something likely to be added to the markdown preview package, it seems more like a potential autocomplete-plus extension specifically targeting images, closing it out here.
