### ISSUE TITLE
Split preview to horizontal (by default?)

### ISSUE THREAD

**Issue by brntbeer** [atom/markdown-preview#99]
Currently when viewing rendered markdown, it splits into a pane to my right. If I don't have 2 30" cinema displays, I usually can't see all of the rendered text.

Could we either change the default or pre-set a keybinding to make it split down?

**Comment by timbru31** [comment]
I'd like to use this feature, too and had the same issue like @chibicode
Would something like this work?
Open new Panel --> get this panel --> open the file in this panel

(see https://atom.io/docs/api/v0.166.0/Workspace#instance-getBottomPanels)

**Comment by chharvey** [comment]
+1 from me for this request. 99% of the time I use the "elegant" workaround (demo'd by @izuzak 's gif) every time I open Markdown preview. It gets quite tedious.

**Comment by thedaniel** [comment]
IMO this might be worth adding a config option.

**Comment by jacktan1991** [comment]
+1 request for an elegant solution, that's why i choose Atom!!

**Comment by brntbeer** [comment]
Going to close out for now, there's a workaround.

**Comment by acontreras89** [comment]
atom/find-and-replace#585 is quite similar to this issue

**Comment by royhowie** [comment]
@brntbeer The workaround doesn't allow the markdown preview to auto update. The file has to be manually saved to force a refresh.
